name: Release to PyPI

on:
  push:
    tags: ["v*"]

env:
  dists-artifact-name: python-package-distributions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rye project manager
        uses: eifinger/setup-rye@v4
      - name: Build package
        run: |
          rye sync
          rye build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.dists-artifact-name }}
          path: dist/*

  testpypi:
    needs:
      - build

    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/tinyscibio
    permissions:
      id-token: write
    steps:
      - name: Download the distribution packages
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.dists-artifact-name }}
          path: dist/
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          repository-url: https://test.pypi.org/legacy/
